version: '3.1'

services:

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget
      MYSQL_USER: budget
      MYSQL_PASSWORD: budget2023!
    ports:
      - "3306:3306"
    
    volumes: 
        - ./data:/docker-entrypoint-initdb.d